- fix release workflow (#6)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,25 +1,23 @@
 name: Release (Manual Step)
 
 on:
-  workflow_dispatch:
-    inputs:
-      name:
-        description: "Enter - major, minor, patch"
-        default: "patch"
+  release:
+    types:
+      - created
 
 jobs:
   release:
     runs-on: ubuntu-latest
     steps:
 
-      - name: Check if provided input is valid
-        run: |
-          echo "Semantic Version: ${{ github.event.inputs.name }}"
-          VERSION=${{ github.event.inputs.name }}
-          if [ "$VERSION" != "major" ] && [ "$VERSION" != "minor" ] && [ "$VERSION" != "patch" ]; then
-              echo "Error: Provided input string must be 'major', 'minor', or 'patch'"
-              exit 1
-          fi
+#      - name: Check if provided input is valid
+#        run: |
+#          echo "Semantic Version: ${{ github.event.inputs.name }}"
+#          VERSION=${{ github.event.inputs.name }}
+#          if [ "$VERSION" != "major" ] && [ "$VERSION" != "minor" ] && [ "$VERSION" != "patch" ]; then
+#              echo "Error: Provided input string must be 'major', 'minor', or 'patch'"
+#              exit 1
+#          fi
 
       # Checkout code from repo
       - name: Checkout repo
@@ -34,46 +32,46 @@ jobs:
         with:
           go-version: '1.22' # The Go version to download (if necessary) and use
 
-      # Double check Go version
-      - name: Go version
-        id: Version
-        run: go version
+#      # Double check Go version
+#      - name: Go version
+#        id: Version
+#        run: go version
+#
+#      # Download Go dependencies
+#      - name: Go download
+#        run: go mod download
 
-      # Download Go dependencies
-      - name: Go download
-        run: go mod download
+#      - name: Create dry tag
+#        uses: anothrNick/github-tag-action@1.69.0
+#        id: semver-tag-dry
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          WITH_V: true
+#          INITIAL_VERSION: 1.0.0
+#          RELEASE_BRANCHES: master
+#          DEFAULT_BUMP: ${{ github.event.inputs.name }}
+#          PRERELEASE: false
+#          DRY_RUN: true # Only get the tag - dry
+#          VERBOSE: false
 
-      - name: Create dry tag
-        uses: anothrNick/github-tag-action@1.69.0
-        id: semver-tag-dry
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          WITH_V: true
-          INITIAL_VERSION: 1.0.0
-          RELEASE_BRANCHES: master
-          DEFAULT_BUMP: ${{ github.event.inputs.name }}
-          PRERELEASE: false
-          DRY_RUN: true # Only get the tag - dry
-          VERBOSE: false
+#      # Echo version
+#      - name: Echo version
+#        run: |
+#          echo ${{ steps.semver-tag-dry.outputs.tag }}
 
-      # Echo version
-      - name: Echo version
-        run: |
-          echo ${{ steps.semver-tag-dry.outputs.tag }}
-
-      # Introduce new tag (for real)
-      - name: Bump version and push tag
-        uses: anothrNick/github-tag-action@1.69.0
-        id: semver-tag
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          WITH_V: true
-          INITIAL_VERSION: 1.0.0
-          RELEASE_BRANCHES: main
-          DEFAULT_BUMP: ${{ github.event.inputs.name }}
-          PRERELEASE: false
-          DRY_RUN: false # Not dry
-          VERBOSE: true
+#      # Introduce new tag (for real)
+#      - name: Bump version and push tag
+#        uses: anothrNick/github-tag-action@1.69.0
+#        id: semver-tag
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          WITH_V: true
+#          INITIAL_VERSION: 1.0.0
+#          RELEASE_BRANCHES: main
+#          DEFAULT_BUMP: ${{ github.event.inputs.name }}
+#          PRERELEASE: false
+#          DRY_RUN: false # Not dry
+#          VERBOSE: true
 
       # Run goreleaser to create new binaries
       - name: Run GoReleaser
@@ -83,6 +81,6 @@ jobs:
           args: release --clean
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          RELEASE_VERSION: ${{ steps.semver-tag.outputs.tag }}
-          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          NO_CREATE_CHANGELOG: false
+#          RELEASE_VERSION: ${{ steps.semver-tag.outputs.tag }}
+#          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+#          NO_CREATE_CHANGELOG: false
